// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BookmarkStudio
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BookmarkStudioString = "78198409-af4c-486d-9caf-7ee074cf1041";
        public static Guid BookmarkStudio = new Guid(BookmarkStudioString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BookmarkManagerToolbar = 0x1000;
        public const int BookmarkManagerToolbarGroup = 0x1001;
        public const int OpenBookmarkManagerCommand = 0x0100;
        public const int RefreshBookmarkManagerCommand = 0x0101;
        public const int ExportBookmarksCommand = 0x0404;
        public const int DeleteBookmarkCommand = 0x0407;
    }
}
