// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BookmarkStudio
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BookmarkStudioString = "78198409-af4c-486d-9caf-7ee074cf1041";
        public static Guid BookmarkStudio = new Guid(BookmarkStudioString);

        public const string guidEditorCommandsString = "160961b3-909d-4b28-9353-a1bef587b4a6";
        public static Guid guidEditorCommands = new Guid(guidEditorCommandsString);

        public const string VSStd2KCmdIDString = "1496a755-94de-11d0-8c3f-00c04fc2aae2";
        public static Guid VSStd2KCmdID = new Guid(VSStd2KCmdIDString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BookmarkManagerToolbar = 0x1000;
        public const int BookmarkManagerToolbarRefreshGroup = 0x1001;
        public const int BookmarkManagerToolbarNewItemsGroup = 0x1002;
        public const int BookmarkManagerToolbarDeleteGroup = 0x1003;
        public const int BookmarkManagerToolbarSettingsGroup = 0x1004;
        public const int SettingsMenu = 0x1010;
        public const int SettingsMenuGroup = 0x1011;
        public const int SettingsMenuOptionsGroup = 0x1012;
        public const int OpenBookmarkManagerCommand = 0x0100;
        public const int AddBookmarkCommand = 0x0102;
        public const int RefreshBookmarkManagerCommand = 0x0101;
        public const int AddFolderCommand = 0x0103;
        public const int ExportBookmarksCommand = 0x0404;
        public const int GoToSlot1Command = 0x0500;
        public const int GoToSlot2Command = 0x0501;
        public const int GoToSlot3Command = 0x0502;
        public const int GoToSlot4Command = 0x0503;
        public const int GoToSlot5Command = 0x0504;
        public const int GoToSlot6Command = 0x0505;
        public const int GoToSlot7Command = 0x0506;
        public const int GoToSlot8Command = 0x0507;
        public const int GoToSlot9Command = 0x0508;
        public const int TogglePromptForNameCommand = 0x0600;
        public const int OpenSettingsCommand = 0x0601;
        public const int BookmarkManagerToolbarFilterGroup = 0x1005;
        public const int FilterByColorMenu = 0x1020;
        public const int FilterByColorMenuGroup = 0x1021;
        public const int MarginContextMenuBookmarkGroup = 0x1022;
        public const int FilterByColorAllCommand = 0x0700;
        public const int FilterByColorBlueCommand = 0x0701;
        public const int FilterByColorRedCommand = 0x0702;
        public const int FilterByColorOrangeCommand = 0x0703;
        public const int FilterByColorYellowCommand = 0x0704;
        public const int FilterByColorGreenCommand = 0x0705;
        public const int FilterByColorPurpleCommand = 0x0706;
        public const int FilterByColorPinkCommand = 0x0707;
        public const int FilterByColorTealCommand = 0x0708;
        public const int StandardToolbarBookmarkGroup = 0x1030;
        public const int BookmarkSlotsMenu = 0x1031;
        public const int BookmarkSlotsMenuGroup = 0x1032;
        public const int BookmarkSlotsMenuGoToGroup = 0x1033;
        public const int LeftMarginContextMenu = 0x0066;
        public const int ToggleBookmark = 0x004C;
    }
}
