// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BookmarkStudio
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string BookmarkStudioString = "78198409-af4c-486d-9caf-7ee074cf1041";
        public static Guid BookmarkStudio = new Guid(BookmarkStudioString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BookmarkManagerToolbar = 0x1000;
        public const int BookmarkManagerToolbarGroup = 0x1001;
        public const int OpenBookmarkManagerCommand = 0x0100;
        public const int AddBookmarkCommand = 0x0102;
        public const int RefreshBookmarkManagerCommand = 0x0101;
        public const int AddFolderCommand = 0x0103;
        public const int ExportBookmarksCommand = 0x0404;
        public const int DeleteBookmarkCommand = 0x0407;
        public const int ClearAllBookmarksCommand = 0x0408;
        public const int GoToSlot1Command = 0x0500;
        public const int GoToSlot2Command = 0x0501;
        public const int GoToSlot3Command = 0x0502;
        public const int GoToSlot4Command = 0x0503;
        public const int GoToSlot5Command = 0x0504;
        public const int GoToSlot6Command = 0x0505;
        public const int GoToSlot7Command = 0x0506;
        public const int GoToSlot8Command = 0x0507;
        public const int GoToSlot9Command = 0x0508;
    }
}
